server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/diary
    username: csw
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

logging:
  level:
    p6spy: info

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:5173